spring.application.name=Lab2

server.port=8080

app.greeting=Hello from Lab2! Welcome to Spring Boot.

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.datasource.access=unrestricted

app.datasource.file-path=data/default-data.csv
app.datasource.file-format=csv
app.datasource.delimiter=,
app.datasource.has-header=true
